### ISSUE TITLE
How to use json in jade

### ISSUE THREAD

**Issue by HenrikFricke** [Jimdo/template-boilerplate#6]
Collection of google stuff how to do...

**Comment by HenrikFricke** [comment]
http://stackoverflow.com/questions/27313107/gulp-using-gulp-jade-with-gulp-data

**Comment by HenrikFricke** [comment]
It could work with: https://www.npmjs.com/package/gulp-data

**Comment by HenrikFricke** [comment]
Interesting: http://tott-meetup.readthedocs.org/en/latest/sessions/gulpjs.html

**Comment by filtercake** [comment]
https://github.com/Jimdo/rapampel/issues/8#issuecomment-86645684

maybe we should talk more 😆

**Comment by HenrikFricke** [comment]
@filtercake haha cool, i will come to you if i have questions ;) thanks!

**Comment by HenrikFricke** [comment]
Works perfect!
